In [ ]:
import os
os.environ['AOC_SESSION'] = '53616c7465645f5fb344d5631fd38994e76ca613dca9a5c84c0e20e1c3cff65206ce26c3833714663d7a57036891ac56cd74a3e151b23654006ac978993e2cce'

## --- Day 10: Hoof It ---
You all arrive at a Lava Production Facility on a floating island in the sky. As the others begin to search the massive industrial complex, you feel a small nose boop your leg and look down to discover a reindeer wearing a hard hat.

The reindeer is holding a book titled "Lava Island Hiking Guide". However, when you open the book, you discover that most of it seems to have been scorched by lava! As you're about to ask how you can help, the reindeer brings you a blank topographic map of the surrounding area (your puzzle input) and looks up at you excitedly.

Perhaps you can help fill in the missing hiking trails?

The topographic map indicates the height at each position using a scale from 0 (lowest) to 9 (highest). For example:
```
0123
1234
8765
9876
```
Based on un-scorched scraps of the book, you determine that a good hiking trail is as long as possible and has an even, gradual, uphill slope. For all practical purposes, this means that a hiking trail is any path that starts at height 0, ends at height 9, and always increases by a height of exactly 1 at each step. Hiking trails never include diagonal steps - only up, down, left, or right (from the perspective of the map).

You look up from the map and notice that the reindeer has helpfully begun to construct a small pile of pencils, markers, rulers, compasses, stickers, and other equipment you might need to update the map with hiking trails.

A trailhead is any position that starts one or more hiking trails - here, these positions will always have height 0. Assembling more fragments of pages, you establish that a trailhead's score is the number of 9-height positions reachable from that trailhead via a hiking trail. In the above example, the single trailhead in the top left corner has a score of 1 because it can reach a single 9 (the one in the bottom left).

This trailhead has a score of 2:
```
...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
```
(The positions marked . are impassable tiles to simplify these examples; they do not appear on your actual topographic map.)

This trailhead has a score of 4 because every 9 is reachable via a hiking trail except the one immediately to the left of the trailhead:
```
..90..9
...1.98
...2..7
6543456
765.987
876....
987....
```
This topographic map contains two trailheads; the trailhead at the top has a score of 1, while the trailhead at the bottom has a score of 2:
```
10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01
```
Here's a larger example:
```
89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
```
This larger example has 9 trailheads. Considering the trailheads in reading order, they have scores of 5, 6, 5, 3, 1, 3, 5, 3, and 5. Adding these scores together, the sum of the scores of all trailheads is 36.

The reindeer gleefully carries over a protractor and adds it to the pile. What is the sum of the scores of all trailheads on your topographic map?

**AI Prompt**

can u summarize this problem clearly ?

**AI Response**

Let me break down this hiking trail problem:

1. We have a map with heights from 0-9
2. We need to find "trailheads" (positions with height 0)
3. From each trailhead, we need to find "valid hiking trails" where:
   - You can only move up, down, left, or right (no diagonals)
   - Each step must increase height by exactly 1
   - Trails must start at height 0 and end at height 9
4. For each trailhead, its "score" is the number of height-9 positions you can reach following valid trails
5. The final answer is the sum of all trailhead scores

Would you like me to clarify any part of this before we start thinking about how to solve it?

**AI Prompt**

plan of attack
- read map into a grid 
- find all the 0 positions
- start from each 0 and look at 4 adjacent positions and move a step if any of those are the next number. keep traversing till u hit 9 or return empty 
- count up all 9s reached from 0 
does that sound good ?

**AI Response**

Yes, that's a solid plan! Let's break it down even further to make sure we have all the details:

1. Reading the map:
   - Convert input into a 2D grid/array
   - Could use a list of lists or numpy array

2. Finding trailheads:
   - Scan grid for all positions where value = 0
   - Store their coordinates (row, col)

3. Path finding from each trailhead:
   - For each 0, start a search
   - Check 4 directions (up, down, left, right)
   - Only move if next position = current + 1
   - Keep track of visited 9s
   - Could use either DFS or BFS for this search

4. Scoring:
   - For each trailhead, count unique 9s reached
   - Sum all scores

Would you like to start with implementing any particular part? I can help guide you through the steps.

**AI Prompt**

why do we need to keep track of visited 9s at all ? don't we just need to know how many times we reached 9 ? or is it coz we might end up at te same 9 and that doesn't count as a new trail ?

**AI Response**

Exactly right! We need to track unique 9s because reaching the same 9 position multiple times from the same trailhead shouldn't count multiple times in the score.

For example, in this small map:
```
0123
1239
```
From the 0, we could have two different paths that both reach the same 9:
- 0→1→2→3→9
- 0→1→2→3→2→3→9

But this trailhead's score would be 1, not 2, because it's the same 9 position.

Does that help explain why we need to track which specific 9s we've reached rather than just counting how many times we hit 9?

**AI Prompt**

ok what does it mean to say either use dfs or bfs for the search ?

**AI Response**

DFS (Depth-First Search) and BFS (Breadth-First Search) are two different ways to explore paths in a graph or grid:

DFS:
- Goes as far as possible along one path before backtracking
- Like exploring a maze by always going as deep as you can, then backing up when stuck
- Usually implemented using recursion or a stack

BFS:
- Explores all possible moves at the current distance before going further
- Like a ripple spreading out from the start position
- Usually implemented using a queue

For this problem, either would work since we want to find ALL possible paths from 0 to 9. The main difference would be the order in which we discover the paths.

Would you like me to explain more about how either of these would work for this specific problem?

**AI Prompt**

ok first lets write a function that reads input into a numpy array so i can get comfortable with numpy. whats the most pythonic way to read in this in ?

**AI Response**

For reading the input into a numpy array, we can use numpy's built-in functions. Here are a couple of approaches we could use:

1. We could read each line as a string and convert each character to an integer
2. We could use numpy's array() function directly with a list comprehension

Would you like to try writing this yourself first? I can provide hints or guidance as needed. Let me know if you'd prefer to see a specific approach demonstrated.

The input format looks like:
```
89010123
78121874
...
```
How would you like to proceed?

## definiing all the inputs

In [ ]:
sample_input1 = """0123
1234
8765
9876"""

sample_input2 = """...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9"""

sample_input3 = """10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01"""

sample_input4 = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732"""

from aocd import get_data
aoc_input = get_data(day=10, year=2024)

In [ ]:
import numpy as np

sinput = sample_input1

flag = 0
for line in sinput.splitlines():
    flds = line.split()
    if not flag:

  Cell In[1], line 9
    
    ^
SyntaxError: incomplete input



**AI Prompt**

actually go ahead and show me the code to read this input into a np 2d array

**AI Response**

Here's a clean way to read the input into a numpy array:

```python
import numpy as np

def read_grid(input_str):
    # Split into lines and convert each character to int using list comprehension
    grid = [[int(c) for c in line] for line in input_str.splitlines()]
    return np.array(grid)

# Test it
grid = read_grid(sample_input1)
print(grid)
```

This will create a 2D numpy array where each character becomes an integer. Would you like me to explain how any part of this works? Or would you like to try using it with one of the other sample inputs?

## read input into a grid

In [ ]:
import numpy as np

def read_grid(input_str):
    def convert(c):
        return -1 if c == '.' else int(c)  # or any other value you want for '.'
    
    grid = [[convert(c) for c in line] for line in input_str.splitlines()]
    return np.array(grid)


# Test it
grid = read_grid(sample_input1)
print(grid)

[[0 1 2 3]
 [1 2 3 4]
 [8 7 6 5]
 [9 8 7 6]]


**AI Prompt**

how to modify function to also allow for a "." or an int ?

**AI Response**

We can modify the function to handle both "." and integers by adding a condition in the conversion. Here's how:

```python
def read_grid(input_str):
    def convert(c):
        return -1 if c == '.' else int(c)  # or any other value you want for '.'
    
    grid = [[convert(c) for c in line] for line in input_str.splitlines()]
    return np.array(grid)

# Test with sample_input2 which has dots
grid = read_grid(sample_input2)
print(grid)
```

I used -1 to represent the dots, but we could use any other value that makes sense for your solution. Would you like to try it with a different value for the dots, or would you like me to explain how any part of this works?

**AI Prompt**

how do we scan a numpy array for a certain value and get coordinates back ? is there a built in np function for that ?

**AI Response**

Yes! NumPy's `np.where()` function is perfect for this. It returns the coordinates (row, col) of all elements matching a condition. Here's how you can use it:

```python
# Returns a tuple of arrays (row_indices, col_indices) where value is 0
zero_positions = np.where(grid == 0)

# To get them as (row,col) pairs you can zip them:
coordinates = list(zip(zero_positions[0], zero_positions[1]))
```

Would you like to try this out to find all the trailheads (zeros) in our test grid?

In [ ]:
def find_zeroes(grid):
    # Returns a tuple of arrays (row_indices, col_indices) where value is 0
    zero_positions = np.where(grid == 0)

    # To get them as (row,col) pairs you can zip them:
    coordinates = list(zip(zero_positions[0], zero_positions[1]))
    return coordinates

zeroes = find_zeroes(grid)
print(zeroes)

[(0, 0)]


In [ ]:
grid = read_grid(sample_input2)
print(grid)
zeroes = find_zeroes(grid)
print(zeroes)

[[-1 -1 -1  0 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1  2 -1 -1 -1]
 [ 6  5  4  3  4  5  6]
 [ 7 -1 -1 -1 -1 -1  7]
 [ 8 -1 -1 -1 -1 -1  8]
 [ 9 -1 -1 -1 -1 -1  9]]
[(0, 3)]


In [ ]:
start = zeroes[0]
start

(0, 3)

In [ ]:
def find_valid_steps(grid, pos):
    row, col = pos
    valid = []
    for new_pos in [(row-1, col), (row+1, col), (row, col-1), (row, col+1)]:
        if 0<=new_pos[0]<len(grid) and 0<=new_pos[1]<len(grid[0]):
            valid.append(new_pos)
    return valid

find_valid_steps(grid, start)

[(1, 3), (0, 2), (0, 4)]

In [ ]:
visited=set()
ptr = start
ctr = 0 
while ptr:
    positions = find_valid_steps(grid, ptr)
    for pos in positions:
        if grid[pos[0], pos[1]] == ctr+1:
            ptr = pos
            ctr+=1
        if grid[pos[0], pos[1]]==9:
            visited.add(pos)
            continue

---------------------------------------------------------------------------
TimeoutError                              Traceback (most recent call last)
Cell In[1], line 10
      8     ptr = pos
      9     ctr+=1
---> 10 if grid[pos[0], pos[1]]==9:
     11     visited.add(pos)
     12     continue

File /usr/local/lib/python3.11/site-packages/execnb/shell.py:92, in run_cell.<locals>.handler(*args)
---> 92 def handler(*args): raise TimeoutError()

TimeoutError: 


TimeoutError: 

**AI Prompt**

can u help debug

**AI Response**

I see the issue - your code is going into an infinite loop because we're not properly tracking visited positions or breaking the loop. Let's modify the approach:

```python
def find_next_height(grid, current_pos, current_height):
    row, col = current_pos
    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        # Check bounds
        if 0 <= new_row < len(grid) and 0 <= new_col < len(grid[0]):
            # Check if it's the next height we want
            if grid[new_row, new_col] == current_height + 1:
                return (new_row, new_col)
    return None

def find_paths(grid, start):
    nines = set()
    current_height = 0
    pos = start
    
    while pos and current_height < 9:
        next_pos = find_next_height(grid, pos, current_height)
        if next_pos is None:
            break
        pos = next_pos
        current_height += 1
        if current_height == 9:
            nines.add(pos)
            
    return len(nines)
```

Would you like me to explain how this works, or would you like to try running it first?

The main changes are:
1. Separate function to find the next valid position
2. Clear termination conditions
3. Only moving to exactly height+1
4. Tracking nine positions found

In [ ]:
def find_next_height(grid, current_pos, current_height):
    row, col = current_pos
    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        # Check bounds
        if 0 <= new_row < len(grid) and 0 <= new_col < len(grid[0]):
            # Check if it's the next height we want
            if grid[new_row, new_col] == current_height + 1:
                return (new_row, new_col)
    return None

def find_paths(grid, start):
    nines = set()
    current_height = 0
    pos = start
    print("start at:", start)
    while pos and current_height < 9:
        next_pos = find_next_height(grid, pos, current_height)
        print("next pos:", next_pos)
        if next_pos is None:
            break
        pos = next_pos
        current_height += 1
        if current_height == 9:
            nines.add(pos)
            print("adding to 9s)")
            
    return len(nines)

In [ ]:
find_paths(grid, start)

1

In [ ]:
grid = read_grid(sample_input2)
print(grid)
zeroes = find_zeroes(grid)
print(zeroes)
for start in zeroes:
    print(find_paths(grid, start))

[[-1 -1 -1  0 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1  2 -1 -1 -1]
 [ 6  5  4  3  4  5  6]
 [ 7 -1 -1 -1 -1 -1  7]
 [ 8 -1 -1 -1 -1 -1  8]
 [ 9 -1 -1 -1 -1 -1  9]]
[(0, 3)]
start at: (0, 3)
next pos: (1, 3)
next pos: (2, 3)
next pos: (3, 3)
next pos: (3, 2)
next pos: (3, 1)
next pos: (3, 0)
next pos: (4, 0)
next pos: (5, 0)
next pos: (6, 0)
adding to 9s)
1


**AI Prompt**

we are not backtracking to trace the other path here. not a true bfs or dfs ? can u fix

**AI Response**

Ah yes, you're absolutely right! We're only finding one path when we need to find all possible paths. Let's modify it to use a proper DFS (depth-first search) approach:

```python
def find_paths_dfs(grid, pos, current_height=0, nines=None):
    if nines is None:
        nines = set()
    
    row, col = pos
    
    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        
        # Check bounds and next height
        if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
            if grid[new_row, new_col] == current_height + 1:
                if current_height + 1 == 9:
                    nines.add((new_row, new_col))
                else:
                    find_paths_dfs(grid, (new_row, new_col), current_height + 1, nines)
    
    return len(nines)
```

The key changes are:
1. Using recursion to explore all possible paths
2. Keeping track of nines across all paths
3. Each position that's height+1 gets explored, not just the first one we find

Would you like to try this version and see if it finds more paths?

**AI Prompt**

def find_paths_dfs(grid, pos, current_height=0, nines=None):
    if nines is None:
        nines = set()
    
    row, col = pos
    
    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        
        # Check bounds and next height
        if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
            if grid[new_row, new_col] == current_height + 1:
                if current_height + 1 == 9:
                    nines.add((new_row, new_col))
                else:
                    find_paths_dfs(grid, (new_row, new_col), current_height + 1, nines)
    
    return len(nines)

**AI Response**

Would you like me to help you test this function with our sample inputs? We can try it with the earlier test cases and see if it finds more paths than the previous version.

Here's how we could test it:

```python
grid = read_grid(sample_input2)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found {score} reachable 9s")
```

Would you like to run this test and see what it finds?

In [ ]:
def find_paths_dfs(grid, pos, current_height=0, nines=None): 
    if nines is None: nines = set()
    row, col = pos

    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        
        # Check bounds and next height
        if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
            if grid[new_row, new_col] == current_height + 1:
                if current_height + 1 == 9:
                    nines.add((new_row, new_col))
                else:
                    find_paths_dfs(grid, (new_row, new_col), current_height + 1, nines)

    return len(nines)

In [ ]:
print(sample_input2)
grid = read_grid(sample_input2)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found {score} reachable 9s")

...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
Grid:
[[-1 -1 -1  0 -1 -1 -1]
 [-1 -1 -1  1 -1 -1 -1]
 [-1 -1 -1  2 -1 -1 -1]
 [ 6  5  4  3  4  5  6]
 [ 7 -1 -1 -1 -1 -1  7]
 [ 8 -1 -1 -1 -1 -1  8]
 [ 9 -1 -1 -1 -1 -1  9]]

Testing each starting position (zeroes):
Starting at (0, 3): found 2 reachable 9s


In [ ]:
print(sample_input3)
grid = read_grid(sample_input3)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found {score} reachable 9s")

10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01
Grid:
[[ 1  0 -1 -1  9 -1 -1]
 [ 2 -1 -1 -1  8 -1 -1]
 [ 3 -1 -1 -1  7 -1 -1]
 [ 4  5  6  7  6  5  4]
 [-1 -1 -1  8 -1 -1  3]
 [-1 -1 -1  9 -1 -1  2]
 [-1 -1 -1 -1 -1  0  1]]

Testing each starting position (zeroes):
Starting at (0, 1): found 1 reachable 9s
Starting at (6, 5): found 2 reachable 9s


In [ ]:
print(sample_input4)
grid = read_grid(sample_input4)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found {score} reachable 9s")

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
Grid:
[[8 9 0 1 0 1 2 3]
 [7 8 1 2 1 8 7 4]
 [8 7 4 3 0 9 6 5]
 [9 6 5 4 9 8 7 4]
 [4 5 6 7 8 9 0 3]
 [3 2 0 1 9 0 1 2]
 [0 1 3 2 9 8 0 1]
 [1 0 4 5 6 7 3 2]]

Testing each starting position (zeroes):
Starting at (0, 2): found 5 reachable 9s
Starting at (0, 4): found 6 reachable 9s
Starting at (2, 4): found 5 reachable 9s
Starting at (4, 6): found 3 reachable 9s
Starting at (5, 2): found 1 reachable 9s
Starting at (5, 5): found 3 reachable 9s
Starting at (6, 0): found 5 reachable 9s
Starting at (6, 6): found 3 reachable 9s
Starting at (7, 1): found 5 reachable 9s


In [ ]:
# on aoc data 
grid = read_grid(aoc_input)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
final_score = 0
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found {score} reachable 9s")
    final_score+=score

print(f"final score={final_score}")

Grid:
[[4 3 2 ... 0 5 8]
 [0 4 5 ... 5 6 9]
 [1 8 7 ... 6 7 8]
 ...
 [8 9 8 ... 5 6 7]
 [1 2 5 ... 4 3 0]
 [0 3 4 ... 3 2 1]]

Testing each starting position (zeroes):
Starting at (0, 4): found 1 reachable 9s
Starting at (0, 11): found 1 reachable 9s
Starting at (0, 25): found 3 reachable 9s
Starting at (0, 33): found 2 reachable 9s
Starting at (0, 47): found 1 reachable 9s
Starting at (0, 57): found 2 reachable 9s
Starting at (1, 0): found 1 reachable 9s
Starting at (1, 13): found 2 reachable 9s
Starting at (1, 15): found 2 reachable 9s
Starting at (1, 24): found 2 reachable 9s
Starting at (1, 38): found 1 reachable 9s
Starting at (1, 45): found 2 reachable 9s
Starting at (1, 51): found 1 reachable 9s
Starting at (1, 52): found 1 reachable 9s
Starting at (1, 54): found 2 reachable 9s
Starting at (2, 18): found 2 reachable 9s
Starting at (2, 19): found 3 reachable 9s
Starting at (2, 21): found 2 reachable 9s
Starting at (2, 24): found 1 reachable 9s
Starting at (2, 42): found 2 reachab

## --- Part Two ---
The reindeer spends a few minutes reviewing your hiking trail map before realizing something, disappearing for a few minutes, and finally returning with yet another slightly-charred piece of paper.

The paper describes a second way to measure a trailhead called its rating. A trailhead's rating is the number of distinct hiking trails which begin at that trailhead. For example:
```
.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
```
The above map has a single trailhead; its rating is 3 because there are exactly three distinct hiking trails which begin at that position:
```
.....0.   .....0.   .....0.
..4321.   .....1.   .....1.
..5....   .....2.   .....2.
..6....   ..6543.   .....3.
..7....   ..7....   .....4.
..8....   ..8....   ..8765.
..9....   ..9....   ..9....
```
Here is a map containing a single trailhead with rating 13:
```
..90..9
...1.98
...2..7
6543456
765.987
876....
987....```
This map contains a single trailhead with rating 227 (because there are 121 distinct hiking trails that lead to the 9 on the right edge and 106 that lead to the 9 on the bottom edge):
```
012345
123456
234567
345678
4.6789
56789.
```
Here's the larger example from before:
```
89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
```
Considering its trailheads in reading order, they have ratings of 20, 24, 10, 4, 1, 4, 5, 8, and 5. The sum of all trailhead ratings in this larger example topographic map is 81.

You're not sure how, but the reindeer seems to have crafted some tiny flags out of toothpicks and bits of paper and is using them to mark trailheads on your topographic map. What is the sum of the ratings of all trailheads?

**AI Prompt**

ok isn't this problem similar to earlier problem but we modify our method ot keep track of the entire path instead of just the visited state 9 ??

**AI Response**

Yes, exactly! The key differences are:

1. Instead of just counting unique 9s reached, we need to count unique *paths* to 9s
2. We need to track the complete path for each successful route to distinguish between different paths to the same 9

We could modify our DFS function to:
- Keep track of the path taken so far
- When we reach a 9, store the complete path instead of just the endpoint
- Count unique paths instead of unique endpoints

Would you like to modify our earlier function to handle this new requirement? We can start by thinking about how to store the paths - perhaps using tuples or strings to represent each unique path?

In [ ]:
def find_paths_dfs(grid, pos, current_height=0, paths=None): 
    if paths is None: 
        paths = set()
        path = set()
    row, col = pos

    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        
        # Check bounds and next height
        if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
            if grid[new_row, new_col] == current_height + 1:
                path.add((new_row, new_col))
                if current_height + 1 == 9:
                    nines.add((new_row, new_col))
                    paths.add(path)
                    path=set()
                else:
                    find_paths_dfs(grid, (new_row, new_col), current_height + 1, paths)

    return paths

In [ ]:
print(sample_input1)
grid = read_grid(sample_input1)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found {score} reachable 9s")

0123
1234
8765
9876
Grid:
[[0 1 2 3]
 [1 2 3 4]
 [8 7 6 5]
 [9 8 7 6]]

Testing each starting position (zeroes):
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[1], line 8
      6 print("\nTesting each starting position (zeroes):")
      7 for start in zeroes:
----> 8     score = find_paths_dfs(grid, start)
      9     print(f"Starting at {start}: found {score} reachable 9s")

Cell In[1], line 20, in find_paths_dfs(grid, pos, current_height, paths)
     18                 path=set()
     19             else:
---> 20                 find_paths_dfs(grid, (new_row, new_col), current_height + 1, paths)
     22 return paths

Cell In[1], line 14, in find_paths_dfs(grid, pos, current_height, paths)
     12 if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
     13     if grid[new_row, new_col] == current_height + 1:
---> 14         path.add((new_row, new_col))
     15   

UnboundLocalError: cannot access local variable 'path' where it is not associated with a value

**AI Prompt**

can u help debug ... i can't figure out how to initialize the path every time ?

**AI Response**

The issue is that we need to pass the path along with the recursion and create a new path for each branch. Here's how we can fix it:

```python
def find_paths_dfs(grid, pos, current_height=0, current_path=None, paths=None): 
    if paths is None: 
        paths = set()
    if current_path is None:
        current_path = [pos]  # Start with current position
        
    row, col = pos

    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        new_pos = (new_row, new_col)
        
        # Check bounds and next height
        if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
            if grid[new_row, new_col] == current_height + 1:
                # Create new path for this branch
                new_path = current_path + [new_pos]
                if current_height + 1 == 9:
                    paths.add(tuple(new_path))  # Convert to tuple to make it hashable
                else:
                    find_paths_dfs(grid, new_pos, current_height + 1, new_path, paths)

    return len(paths)
```

Key changes:
1. Using a list for the path instead of a set (to maintain order)
2. Creating a new path for each recursive call
3. Converting path to tuple when adding to paths set (so it can be hashed)
4. Passing the current path along with recursion

Would you like to try this version?

In [ ]:
def find_paths_dfs(grid, pos, current_height=0, current_path=None, paths=None): 
    if paths is None: 
        paths = set()
    if current_path is None:
        current_path = [pos]  # Start with current position
        
    row, col = pos

    # Check all 4 directions
    for dr, dc in [(-1,0), (1,0), (0,-1), (0,1)]:
        new_row, new_col = row + dr, col + dc
        new_pos = (new_row, new_col)
        
        # Check bounds and next height
        if (0 <= new_row < len(grid) and 0 <= new_col < len(grid[0])):
            if grid[new_row, new_col] == current_height + 1:
                # Create new path for this branch
                new_path = current_path + [new_pos]
                if current_height + 1 == 9:
                    paths.add(tuple(new_path))  # Convert to tuple to make it hashable
                else:
                    find_paths_dfs(grid, new_pos, current_height + 1, new_path, paths)

    return len(paths)

In [ ]:
sample_input1 = """.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9...."""
print(sample_input1)
grid = read_grid(sample_input1)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found rating of {score}")

.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
Grid:
[[-1 -1 -1 -1 -1  0 -1]
 [-1 -1  4  3  2  1 -1]
 [-1 -1  5 -1 -1  2 -1]
 [-1 -1  6  5  4  3 -1]
 [-1 -1  7 -1 -1  4 -1]
 [-1 -1  8  7  6  5 -1]
 [-1 -1  9 -1 -1 -1 -1]]

Testing each starting position (zeroes):
Starting at (0, 5): found rating of 3


In [ ]:
sample_input1 = """..90..9
...1.98
...2..7
6543456
765.987
876....
987...."""
print(sample_input1)
grid = read_grid(sample_input1)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found rating of {score}")

..90..9
...1.98
...2..7
6543456
765.987
876....
987....
Grid:
[[-1 -1  9  0 -1 -1  9]
 [-1 -1 -1  1 -1  9  8]
 [-1 -1 -1  2 -1 -1  7]
 [ 6  5  4  3  4  5  6]
 [ 7  6  5 -1  9  8  7]
 [ 8  7  6 -1 -1 -1 -1]
 [ 9  8  7 -1 -1 -1 -1]]

Testing each starting position (zeroes):
Starting at (0, 3): found rating of 13


In [ ]:
sample_input1 = """012345
123456
234567
345678
4.6789
56789."""
print(sample_input1)
grid = read_grid(sample_input1)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found rating of {score}")

012345
123456
234567
345678
4.6789
56789.
Grid:
[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4 -1  6  7  8  9]
 [ 5  6  7  8  9 -1]]

Testing each starting position (zeroes):
Starting at (0, 0): found rating of 227


In [ ]:
sample_input1 = """89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732"""
print(sample_input1)
grid = read_grid(sample_input1)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
final_rating=0
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found rating of {score}")
    final_rating+=score
print(f"final rating={final_rating}")

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
Grid:
[[8 9 0 1 0 1 2 3]
 [7 8 1 2 1 8 7 4]
 [8 7 4 3 0 9 6 5]
 [9 6 5 4 9 8 7 4]
 [4 5 6 7 8 9 0 3]
 [3 2 0 1 9 0 1 2]
 [0 1 3 2 9 8 0 1]
 [1 0 4 5 6 7 3 2]]

Testing each starting position (zeroes):
Starting at (0, 2): found rating of 20
Starting at (0, 4): found rating of 24
Starting at (2, 4): found rating of 10
Starting at (4, 6): found rating of 4
Starting at (5, 2): found rating of 1
Starting at (5, 5): found rating of 4
Starting at (6, 0): found rating of 5
Starting at (6, 6): found rating of 8
Starting at (7, 1): found rating of 5
final rating=81


In [ ]:
# running on aoc input
grid = read_grid(aoc_input)
zeroes = find_zeroes(grid)
print("Grid:")
print(grid)
print("\nTesting each starting position (zeroes):")
final_rating=0
for start in zeroes:
    score = find_paths_dfs(grid, start)
    print(f"Starting at {start}: found rating of {score}")
    final_rating+=score
print(f"final rating={final_rating}")

Grid:
[[4 3 2 ... 0 5 8]
 [0 4 5 ... 5 6 9]
 [1 8 7 ... 6 7 8]
 ...
 [8 9 8 ... 5 6 7]
 [1 2 5 ... 4 3 0]
 [0 3 4 ... 3 2 1]]

Testing each starting position (zeroes):
Starting at (0, 4): found rating of 1
Starting at (0, 11): found rating of 2
Starting at (0, 25): found rating of 5
Starting at (0, 33): found rating of 3
Starting at (0, 47): found rating of 1
Starting at (0, 57): found rating of 4
Starting at (1, 0): found rating of 1
Starting at (1, 13): found rating of 6
Starting at (1, 15): found rating of 8
Starting at (1, 24): found rating of 3
Starting at (1, 38): found rating of 4
Starting at (1, 45): found rating of 4
Starting at (1, 51): found rating of 2
Starting at (1, 52): found rating of 1
Starting at (1, 54): found rating of 12
Starting at (2, 18): found rating of 6
Starting at (2, 19): found rating of 3
Starting at (2, 21): found rating of 2
Starting at (2, 24): found rating of 1
Starting at (2, 42): found rating of 4
Starting at (3, 9): found rating of 1
Starting at (4,